name: Syntax OK
on: [push]

jobs:
  syntax_ok:
    name: Syntax OK
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby:
          - docker://rubylang/rubyfarm:latest
          - docker://rubylang/ruby:2.7-bionic
    steps:
      - uses: actions/checkout@master
      - name: Test Syntax OK
        uses: ${{ matrix.ruby }}
        with:
          entrypoint: /opt/ruby/bin/ruby
          args: -c snake.rb
      - name: Test Syntax OK (eval)
        uses: ${{ matrix.ruby }}
        with:
          entrypoint: /opt/ruby/bin/ruby
          args: -e 'def eval(src); RubyVM::AbstractSyntaxTree.parse(src) ;end; load "snake.rb"'
